name: DockerHub

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 20 1 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: PHP 7.4 Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: php7.4/Dockerfile
          push: true
          tags: splintnet/alpine-php:php7.4

      - name: PHP 8.0 Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: php8.0/Dockerfile
          push: true
          tags: splintnet/alpine-php:php8.0

      - name: PHP 8.1 Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: php8.1/Dockerfile
          push: true
          tags: splintnet/alpine-php:php8.1

      - name: PHP 8.2 Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: php8.2/Dockerfile
          push: true
          tags: splintnet/alpine-php:latest,splintnet/alpine-php:php8.2
