name: ci

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: PHP 7.4 Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./php7.4
          push: true
          tags: splintnet/alpine-php:latest,splintnet/alpine-php:php7.4
      -
        name: PHP 8.0 Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./php8.0
          push: true
          tags: splintnet/alpine-php:php8.0
